name: "✨ Feature"
description: "Para novas funcionalidades em relação ao repositório de `queries-basedosdados`"
title: "[Feature] <title>"
labels: 
  - "enhancement"
  - "triage"

body:
  - type: textarea
    attributes:
      label: "Descreva a sua feature"
      description: "Descreva de forma clara e concisa."
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Alternativa proposta"
      description: "Descreva a sua proposta de para o funcionamento da feature."
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Como a BD se beneficia com a feature?"
      description: "Descreva como a BD se beneficia com a feature."
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Precisará de contribuição de terceiros?"
      description: "Descreva se a feature precisará de contribuição de terceiros, se sim, cite-lo na issue."

  - type: textarea
    attributes:
      label: "Outras considerações"
      description: "Descreva outras considerações relevantes sobre a feature."